# permissions for end users to view blogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blog-viewer-role
rules:
- apiGroups:
  - web.helloworld
  resources:
  - blogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.helloworld
  resources:
  - blogs/status
  verbs:
  - get
