# permissions for end users to edit webs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-editor-role
rules:
- apiGroups:
  - web.helloworld
  resources:
  - webs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.helloworld
  resources:
  - webs/status
  verbs:
  - get
